# Generated by Django 3.2.12 on 2022-02-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_task',
            field=models.DateField(default='1996-08-01'),
            preserve_default=False,
        ),
    ]
